CREATE DATABASE VENTAS;
USE VENTAS;

-- SE CREA LA TABLA DE EMPLEADOS CON SUS RESPECTIVOS VALORES
CREATE TABLE EMPLEADOS(
	ID_EMPLEADO		INT			PRIMARY KEY AUTO_INCREMENT,
    NOMBRE			VARCHAR(50)	NOT NULL,
    APELLIDOS		VARCHAR(70)	NOT NULL,
    USERNAME		VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD		CHAR(64) 	NOT NULL,
    SUPER_USER		BOOLEAN		NOT NULL DEFAULT FALSE,
    ACTIVO			BOOLEAN		NOT NULL DEFAULT TRUE
);

-- SE CREA LA TABLA DE LIBROS CON SUS RESPECTIVOS VALORES
CREATE TABLE LIBROS(
	ISBN		VARCHAR(13)		PRIMARY KEY,
    NOMBRE		VARCHAR(50)		NOT NULL,
    AUTOR		VARCHAR(100)	NOT NULL,
    DESCRIPCION VARCHAR(1000),
    PRECIO		DECIMAL(10,2)	NOT NULL	CHECK (PRECIO >= 0),
    STOCK		INT 			NOT NULL	DEFAULT 0	CHECK (STOCK >= 0)
);
-- SE CREA UNA TABLA DE VENTAS QUE ENLAZA UNA VENTA CON UN EMPLEADO
CREATE TABLE VENTAS(
	ID_VENTA	INT 		PRIMARY KEY AUTO_INCREMENT,
    ID_EMPLEADO	INT			NOT NULL,
    FECHA		DATETIME	NOT NULL DEFAULT NOW(),
    TOTAL		DECIMAL(10,2)	NOT NULL,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO)
);

-- SE CREA UNA TABLA QUE RELACIONA LA CANTIDAD POR LIBRO DE UNA VENTA
CREATE TABLE DETALLE_VENTA(
	ID_VENTA	INT				NOT NULL,
    ISBN		VARCHAR(13)		NOT NULL,
    CANTIDAD	INT				NOT NULL	CHECK(CANTIDAD>0),
    PRECIO		DECIMAL(10,2)	NOT NULL,
    IMPORTE		DECIMAL(10,2)	NOT NULL,
    PRIMARY KEY(ID_VENTA, ISBN),
    FOREIGN KEY (ID_VENTA) REFERENCES VENTAS (ID_VENTA),
    FOREIGN KEY (ISBN) REFERENCES LIBROS (ISBN)
);

-- SE CREA UNA TABLA DE AUDITORIA PARA SABER QUIEN Y CUANDO DE REALIZA UN CAMBIO A UN LIBRO
CREATE TABLE AUDITORIA(
	ID_AUDITORIA	INT									PRIMARY KEY AUTO_INCREMENT,
    TIPO			ENUM('INSERT','UPDATE','DELETE')	NOT NULL,
    USUARIO			VARCHAR(150) 						NOT NULL,
    FECHA			DATETIME							NOT NULL,
    VALOR_ANTERIOR	TEXT,
    VALOR_NUEVO		TEXT
);

-- UN PROCEDIMIENTO PARA LA CREACIÓN DE UN EMPLEADO
DELIMITER $$
CREATE PROCEDURE SP_CREAR_EMPLEADO(
    IN  P_NOMBRE        VARCHAR(50),
    IN  P_APELLIDOS     VARCHAR(70),
    IN  P_USERNAME      VARCHAR(50),
    IN  P_PASSWORD      CHAR(64),
    IN  P_SUPER_USER    BOOLEAN
)
BEGIN
    INSERT INTO EMPLEADOS (NOMBRE, APELLIDOS, USERNAME, PASSWORD, SUPER_USER)
    VALUES(P_NOMBRE, P_APELLIDOS, P_USERNAME, P_PASSWORD, P_SUPER_USER);
END $$
DELIMITER ;

-- UN PROCEDIMIENTO PARA LA ACTUALIZACIÓN EN UN EMPLEADO EN BASE DE SU ID
DELIMITER $$
CREATE PROCEDURE SP_ACTUALIZAR_EMPLEADO(
	IN	P_ID_EMPLEADO INT,
	IN	P_NOMBRE	VARCHAR(50),
    IN 	P_APELLIDOS	VARCHAR(70),
    IN 	P_USERNAME	VARCHAR(50),
    IN 	P_PASSWORD	CHAR(64),
    IN 	P_SUPER_USER	BOOLEAN,
    IN 	P_ACTIVO	BOOLEAN
)
BEGIN
	UPDATE EMPLEADOS SET 
		NOMBRE=P_NOMBRE,
		APELLIDOS=P_APELLIDOS,
		USERNAME=P_USERNAME,
		PASSWORD = IF(LENGTH(P_PASSWORD) > 0, P_PASSWORD, PASSWORD),
		SUPER_USER=P_SUPER_USER,
		ACTIVO=P_ACTIVO 
	WHERE P_ID_EMPLEADO=ID_EMPLEADO;
END $$
DELIMITER ;

-- UN PROCEDIMIENTO QUE HACER UN BORRADO LÓGICO DE UN EMPLEADO EN BASE SU USERNAME
DELIMITER $$
CREATE PROCEDURE SP_ELIMINAR_EMPLEADO(
	IN P_USERNAME	VARCHAR(50)
)
BEGIN
	UPDATE EMPLEADOS SET 
		ACTIVO = FALSE 
	WHERE USERNAME=P_USERNAME;
END $$
DELIMITER ;

-- SE INSERTA UN EMPLEADO DE MUESTRA

-- UN PROCEDIMIENTO QUE CREA LA VENTA Y NOS REGRESA SU ÚLTIMO ID INSERTADO PARA CREAR LOS DETALLES DE LA VENTA
DELIMITER $$
CREATE PROCEDURE SP_CREAR_VENTA(
	IN 	P_ID_EMPLEADO	INT,
    OUT	P_ID_VENTA	INT
)
BEGIN
		INSERT INTO VENTAS VALUES(
			NULL,P_ID_EMPLEADO, NOW(), 0.00
        );
        
        SET P_ID_VENTA = LAST_INSERT_ID();
END $$
DELIMITER ;

-- PARA EL LLENADO DEL DETALLE DE VENTA
DELIMITER $$
CREATE PROCEDURE SP_DETALLE_VENTA(
    IN  P_ID_VENTA      INT,
    IN  P_ISBN          VARCHAR(13),
    IN  P_CANTIDAD      INT
)
BEGIN
    DECLARE V_PRECIO    DECIMAL(10,2);
    DECLARE V_IMPORTE   DECIMAL(10,2);
    
    SELECT PRECIO INTO V_PRECIO FROM LIBROS WHERE ISBN = P_ISBN;
    
    SET V_IMPORTE = V_PRECIO * P_CANTIDAD;
    
    INSERT INTO DETALLE_VENTA VALUES(P_ID_VENTA, P_ISBN, P_CANTIDAD, V_PRECIO, V_IMPORTE);
    SET @NO_AUDITAR = TRUE;
    UPDATE LIBROS SET STOCK = STOCK - P_CANTIDAD WHERE ISBN = P_ISBN;
    SET @NO_AUDITAR = FALSE;
    UPDATE VENTAS SET TOTAL = TOTAL + V_IMPORTE WHERE ID_VENTA = P_ID_VENTA;
END $$
DELIMITER ;
-- EL TRIGGER QUE SE UTILIZA AL ACTUALIZAR UN LIBRO PARA AÑADIRSE A LA TABLA DE AUDITORIAS
DELIMITER $$
CREATE TRIGGER TRG_AUDITORIA_UPDATE
AFTER UPDATE ON LIBROS
FOR EACH ROW
BEGIN
	IF(IFNULL(@NO_AUDITAR,FALSE) IS FALSE) THEN
		BEGIN
			DECLARE NUEVO TEXT;
			DECLARE ANTERIOR TEXT;
			
			SET NUEVO = CONCAT("ISBN: ", NEW.ISBN, " | NOMBRE: ", NEW.NOMBRE, " | PRECIO: ", NEW.PRECIO, " | STOCK: ", NEW.STOCK);
			SET ANTERIOR = CONCAT("ISBN: ", OLD.ISBN, " | NOMBRE: ", OLD.NOMBRE, " | PRECIO: ", OLD.PRECIO, " | STOCK: ", OLD.STOCK);
			
			INSERT INTO AUDITORIA VALUES(NULL, 'UPDATE', USER(), NOW(), ANTERIOR, NUEVO);
		END;
    END IF;
END $$

-- EL TRIGGER QUE SE UTILIZA AL AGREGAR UN LIBRO PARA AÑADIRSE A LA TABLA DE AUDITORIAS
CREATE TRIGGER TRG_AUDITORIA_INSERT
AFTER INSERT ON LIBROS
FOR EACH ROW
BEGIN
    DECLARE NUEVO TEXT;
    SET NUEVO = CONCAT("ISBN: ", NEW.ISBN, " | NOMBRE: ", NEW.NOMBRE, " | PRECIO: ", NEW.PRECIO, " | STOCK: ", NEW.STOCK);
    INSERT INTO AUDITORIA VALUES(NULL, 'INSERT', USER(), NOW(), 'N/A', NUEVO);
END $$

-- EL TRIGGER QUE SE UTILIZA AL ELIMINAR UN LIBRO PARA AÑADIRSE A LA TABLA DE AUDITORIAS
CREATE TRIGGER TRG_AUDITORIA_DELETE
AFTER DELETE ON LIBROS
FOR EACH ROW
BEGIN
    DECLARE ANTERIOR TEXT;
    SET ANTERIOR = CONCAT("ISBN: ", OLD.ISBN, " | NOMBRE: ", OLD.NOMBRE, " | PRECIO: ", OLD.PRECIO, " | STOCK: ", OLD.STOCK);
    INSERT INTO AUDITORIA VALUES(NULL, 'DELETE', USER(), NOW(), ANTERIOR, 'N/A');
END $$
DELIMITER ;

ALTER TABLE LIBROS ADD COLUMN ACTIVO BOOLEAN NOT NULL DEFAULT TRUE;

DELIMITER $$
DROP PROCEDURE IF EXISTS SP_AGREGAR_LIBRO $$

CREATE PROCEDURE SP_CREAR_LIBRO(
    IN P_ISBN           VARCHAR(13),
    IN P_NOMBRE         VARCHAR(50),
    IN P_AUTOR          VARCHAR(100),
    IN P_DESCRIPCION    VARCHAR(1000),
    IN P_PRECIO         DECIMAL(10,2),
    IN P_STOCK          INT
)
BEGIN
	INSERT INTO LIBROS
	VALUES (P_ISBN, P_NOMBRE, P_AUTOR, P_DESCRIPCION, P_PRECIO, P_STOCK, TRUE);
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE SP_ACTUALIZAR_LIBRO(
    IN P_ISBN           VARCHAR(13),
    IN P_NOMBRE         VARCHAR(50),
    IN P_AUTOR          VARCHAR(100),
    IN P_DESCRIPCION    VARCHAR(1000),
    IN P_PRECIO         DECIMAL(10,2),
    IN P_STOCK          INT,
    IN P_ACTIVO			BOOLEAN
)
BEGIN
    UPDATE LIBROS SET 
        NOMBRE = P_NOMBRE,
        AUTOR = P_AUTOR,
        DESCRIPCION = P_DESCRIPCION,
        PRECIO = P_PRECIO,
        STOCK = P_STOCK,
        ACTIVO = P_ACTIVO
    WHERE ISBN = P_ISBN;
END $$
DELIMITER ;